spring.application.name=AIVideoGeneratorBackend

spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}

jwt.secret = ${JWT_KEY}


spring.jpa.hibernate.ddl-auto=update

gemini.api.key=${DEV_API_KEY}
google.veo3.api.key=${DEV_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-pro

logging.level.org.springframework.security.web.FilterChainProxy=DEBUG


video.storage.path=videos/